"""This module defines custom data types and Pydantic models for the runtime.

It ensures data consistency and validation across different modules by providing
centralized, well-defined data structures for plans, tasks, and agent outputs.
"""

from typing import List, Optional, Dict, Any, ForwardRef
from pydantic import BaseModel, Field

class Task(BaseModel):
    """A single actionable step in a plan."""
    id: str = Field(..., description="Unique ID for the task (e.g., 'T-00.1', 'P-A02').")
    description: str = Field(..., description="Detailed description of what to do for this task.")
    role: str = Field(..., description="The role responsible for this task.")
    agent: str = Field(..., description="The agent assigned to this task.")
    deps: List[str] = Field(..., description="List of requirements (task IDs, e.g. ['T-00.4', 'P-B01']).")
    subtasks: Optional[List['Task']] = Field(default=None, description="Sub-tasks breaking down this task further.")

class TaskAction(BaseModel):
    """Action-Verb concept of a task."""
    condition: Optional[str] = Field(default=None, description="Condition to evaluate before executing this task.")
    action_verb: Optional[str] = Field(default=None, description="The action verb (e.g., 'FIND', 'EXECUTE').")
    action_params: List[str] = Field(default_factory=list, description="Parameters for the action.")


class File(BaseModel):
    """Represents a generated file."""
    path: str = Field(..., description="File path or name (e.g., 'src/main.py').")
    content: str = Field(..., description="Full content of the file.")


class Artifact(BaseModel):
    """Output artifact generated by a task."""
    task: str = Field(..., description="ID of the task that produced this artifact (e.g., 'T-10.0').")
    files: List[File] = Field(..., description="Files generated by the task.")


class Role(BaseModel):
    """Definition of an agent's role and goal in a team."""
    title: str = Field(..., description="Title of the role (or an agent's name).")
    purpose: str = Field(..., description="Purpose of the role (or an agent's goal).")


class AgentProfile(BaseModel):
    """Basic profile of an agent."""
    name: str = Field(..., description="Name of the agent (team member).")
    role: str = Field(..., description="Role of the agent (primary, initial).")
    goal: str = Field(..., description="The high-level goal of the agent.")


class Prompt(BaseModel):
    """System prompt assigned to an agent."""
    agent: str = Field(..., description="Name of the agent this prompt is for. Must match exactly an existing agent.")
    role: str = Field(..., description="Role context of the agent.")
    system_prompt: str = Field(..., description="Full text of the system prompt for this agent.")


class Team(BaseModel):
    """Metadata and coordination for the team."""
    notes: str = Field(..., description="General notes or feedback about the team's performance or the plan.")
    prompts: List[Prompt] = Field(default_factory=list, description="A list of new or updated system prompts for any agent in the team.")


class Plan(BaseModel):
    """Overall strategy with reasoning, roles, and tasks."""
    high_level_goal: str = Field(..., description="The main goal this plan is designed to achieve.")
    reasoning: str = Field(..., description="A brief explanation of the plan's structure and strategy.")
    roles: List[Role] = Field(..., description="List of all roles required to execute the plan.")
    tasks: List[Task] = Field(..., description="A step-by-step sequence of tasks to be executed in order.")
    team: Optional[Team] = Field(default=None, description="Updates to team configuration or system prompts.")

class PlanMeta(BaseModel):
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata and parameters for the plan.")


class AgentOutput(BaseModel):
    """Structured output returned by an agent after executing a task."""
    #output: str = Field(..., description="A summary of the work done. Do not include file contents here; use the 'artifact' field instead.")
    output: str = Field(..., description="Text message content (response from agent).")
    artifact: Optional[Artifact] = Field(default=None, description="Any files created or modified by the agent during the task.")
    team: Optional[Team] = Field(default=None, description="Updates to team configuration or system prompts.")
    reasoning: Optional[str] = Field(default=None, description="Explanation of how the agent arrived at this output.")


class Feedback(BaseModel):
    """Represents feedback on an agent's performance for a given task."""
    task_id: str = Field(..., description="The ID of the task for which feedback is provided.")
    agent_name: str = Field(..., description="The name of the agent that executed the task.")
    rating: float = Field(..., description="A numerical rating (e.g., 1-5) of the prompt's effectiveness.")
    comment: str = Field(..., description="A textual comment explaining the rating and suggesting improvements.")
    timestamp: str = Field(..., description="When the feedback was provided.")


if __name__ == "__main__":
    import json
    print(json.dumps(AgentOutput.model_json_schema(), indent=4))
